[package]
name = "ffmpeg-sys"
description = "Rust bindings to ffmpeg!"
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/cosmicexplorer/ffmpeg-rs"
authors = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.59.2"
cc = "1.0"
cfg-if = "1.0.0"
lazy_static = "1"
regex = "1"
spack = { git = "https://github.com/cosmicexplorer/spack-rs", rev = "180073445756490bbbd630da9d4d85438ffac185" }
# spack = { path = "/home/cosmicexplorer/tools/spack-rs" }
tokio = { version = "1.17.0", features = ["full"] }
walkdir = "2"

[features]
default = [
    "libavcodec",
    "libavdevice",
    "libavfilter",
    "libavformat",
    "libavutil",
    "libpostproc",
    "libswresample",
    "libswscale",
  ]

# Platform support.
linux = []
wasm = []

# Modules to enable.
libavcodec = []
libavdevice = []
libavfilter = []
libavformat = []
libavutil = []
libpostproc = []
libswresample = []
libswscale = []
