[package]
name = "ffmpeg-sys"
description = "Rust bindings to ffmpeg!"
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/cosmicexplorer/ffmpeg-rs"
authors = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
spack = { git = "https://github.com/cosmicexplorer/spack-rs", rev = "31e8e076e7af420a1d07fcd99f49966b2f4b81fb" }
